[theme]
primaryColor = "#0b6e99"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7f8"
textColor = "#1a1a1a"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
